# Generated by Django 5.1.15 on 2026-05-18 17:05

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietaryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_of_birth", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "height_cm",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(250),
                        ]
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(30.0),
                            django.core.validators.MaxValueValidator(300.0),
                        ],
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary"),
                            ("light", "Light"),
                            ("moderate", "Moderate"),
                            ("very", "Very Active"),
                            ("athlete", "Athlete"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("lose_weight", "Lose Weight"),
                            ("maintain", "Maintain"),
                            ("gain_muscle", "Gain Muscle"),
                            ("gain_weight_healthy", "Gain Weight (Healthy)"),
                            ("eat_healthier", "Eat Healthier"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "primary_cuisine_region",
                    models.CharField(
                        choices=[
                            ("north_indian", "North Indian"),
                            ("south_indian", "South Indian"),
                            ("east_indian", "East Indian"),
                            ("west_indian", "West Indian"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "secondary_cuisine_preferences",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "spice_tolerance",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("medium", "Medium"),
                            ("hot", "Hot"),
                            ("very_hot", "Very Hot"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "diet_pattern",
                    models.CharField(
                        choices=[
                            ("vegetarian", "Vegetarian"),
                            ("eggetarian", "Eggetarian"),
                            ("non_vegetarian", "Non-Vegetarian"),
                            ("pescatarian", "Pescatarian"),
                            ("vegan", "Vegan"),
                            ("jain", "Jain"),
                        ],
                        max_length=20,
                    ),
                ),
                ("no_onion_garlic", models.BooleanField(default=False)),
                (
                    "allergies",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "dislikes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "daily_food_budget_inr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(3000),
                        ],
                    ),
                ),
                (
                    "weekly_food_budget_inr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(20000),
                        ],
                    ),
                ),
                (
                    "household_size",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "cooking_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekends_only", "Weekends Only"),
                            ("rarely", "Rarely"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "max_prep_time_min",
                    models.PositiveSmallIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=15,
                    ),
                ),
                ("target_calories", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "target_protein_g",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
                ),
                (
                    "target_carbs_g",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
                ),
                (
                    "target_fat_g",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
                ),
                (
                    "target_fiber_g",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dietary Profile",
                "verbose_name_plural": "Dietary Profiles",
                "indexes": [
                    models.Index(fields=["user"], name="profiles_di_user_id_795705_idx"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["allergies"], name="profiles_allergies_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["secondary_cuisine_preferences"],
                        name="profiles_secondary_cuisine_gin",
                    ),
                ],
            },
        ),
    ]
