# Generated by Django 5.1.15 on 2026-05-20 03:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietaryprofile",
            name="daily_food_budget_inr",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("100")),
                    django.core.validators.MaxValueValidator(Decimal("3000")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dietaryprofile",
            name="weekly_food_budget_inr",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("700")),
                    django.core.validators.MaxValueValidator(Decimal("20000")),
                ],
            ),
        ),
    ]
