# Generated by Django 5.1.15 on 2026-05-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_budget_minimum_raise"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietaryprofile",
            name="timezone",
            field=models.CharField(default="Asia/Kolkata", max_length=50),
        ),
    ]
