# Generated by Django 5.1.15 on 2026-05-30 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0003_backfill_protein_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyNutritionSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary_date", models.DateField()),
                ("calories", models.PositiveIntegerField(default=0)),
                ("protein_g", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("carbs_g", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("fat_g", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("fiber_g", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("micronutrients", models.JSONField(default=dict)),
                ("meals_eaten", models.PositiveSmallIntegerField(default=0)),
                ("meals_skipped", models.PositiveSmallIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_nutrition_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "summary_date"], name="dailynutrition_user_date_idx"
                    )
                ],
                "unique_together": {("user", "summary_date")},
            },
        ),
        migrations.CreateModel(
            name="MealLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("log_date", models.DateField(db_index=True)),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("ate_planned", "Ate Planned"),
                            ("ate_substituted", "Ate Substituted"),
                            ("ate_custom", "Ate Custom"),
                            ("skipped", "Skipped"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("servings_eaten", models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ("custom_description", models.CharField(blank=True, max_length=200, null=True)),
                ("custom_calories", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "custom_protein_g",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "custom_carbs_g",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "custom_fat_g",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                ("logged_at", models.DateTimeField(auto_now=True)),
                (
                    "actual_recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "planned_recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "log_date"], name="meallog_user_date_idx")
                ],
                "unique_together": {("user", "log_date", "slot")},
            },
        ),
    ]
