from django.conf import settings
from django.db import models

from core.mixins import TimestampedModel

# ---------------------------------------------------------------------------
# Choice constants
# ---------------------------------------------------------------------------

GEN_BY_RULES = "rules"
GEN_BY_AI = "ai"

GEN_BY_CHOICES = [
    (GEN_BY_RULES, "Rules"),
    (GEN_BY_AI, "AI"),
]

SLOT_BREAKFAST = "breakfast"
SLOT_LUNCH = "lunch"
SLOT_DINNER = "dinner"

SLOT_CHOICES = [
    (SLOT_BREAKFAST, "Breakfast"),
    (SLOT_LUNCH, "Lunch"),
    (SLOT_DINNER, "Dinner"),
]


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------


class MealPlan(TimestampedModel):
    """One day of three recipe slots for a user, generated by the rules engine or AI."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="meal_plans",
    )
    plan_date = models.DateField()
    breakfast = models.ForeignKey(
        "recipes.Recipe",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    lunch = models.ForeignKey(
        "recipes.Recipe",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    dinner = models.ForeignKey(
        "recipes.Recipe",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    generated_by = models.CharField(max_length=10, choices=GEN_BY_CHOICES, default=GEN_BY_RULES)
    generated_at = models.DateTimeField(auto_now_add=True)
    regeneration_count = models.JSONField(default=dict)
    full_plan_regenerations = models.PositiveSmallIntegerField(default=0)

    class Meta:
        unique_together = [("user", "plan_date")]
        indexes = [
            models.Index(fields=["user", "-plan_date"], name="mealplan_user_date_desc"),
        ]

    def __str__(self) -> str:
        return f"MealPlan({self.user_id}, {self.plan_date})"
