# Generated by Django 5.1.15 on 2026-05-23 17:40

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("app_id", models.CharField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("name_hi", models.CharField(blank=True, default="", max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("grain", "Grain"),
                            ("pulse", "Pulse"),
                            ("vegetable", "Vegetable"),
                            ("fruit", "Fruit"),
                            ("dairy", "Dairy"),
                            ("meat", "Meat"),
                            ("fish", "Fish"),
                            ("egg", "Egg"),
                            ("oil_fat", "Oil / Fat"),
                            ("spice", "Spice"),
                            ("nut_seed", "Nut / Seed"),
                            ("sweetener", "Sweetener"),
                            ("beverage", "Beverage"),
                            ("processed", "Processed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("per_100g_nutrition", models.JSONField()),
                (
                    "approximate_price_inr_per_kg",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
                ),
                ("price_as_of_month", models.CharField(blank=True, default="", max_length=7)),
                (
                    "allergen_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "form",
                    models.CharField(
                        choices=[("raw", "Raw"), ("cooked", "Cooked"), ("as_eaten", "As Eaten")],
                        max_length=20,
                    ),
                ),
                (
                    "cooked_yield_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.10")),
                            django.core.validators.MaxValueValidator(Decimal("10.00")),
                        ],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ifct", "IFCT 2017"),
                            ("usda", "USDA FDC"),
                            ("manual", "Manual"),
                            ("composed", "Composed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ifct_code", models.CharField(blank=True, default="", max_length=10)),
                ("ifct_name", models.CharField(blank=True, default="", max_length=200)),
                ("ifct_regn", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("usda_fdc_id", models.IntegerField(blank=True, null=True)),
                ("usda_description", models.CharField(blank=True, default="", max_length=200)),
                ("package_version", models.CharField(blank=True, default="", max_length=60)),
                ("extracted_at", models.DateField(blank=True, null=True)),
                (
                    "confidence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exact", "Exact"),
                            ("good", "Good"),
                            ("approximate", "Approximate"),
                            ("weak", "Weak"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("overlays", models.JSONField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["category"], name="recipes_ing_categor_b99d8e_idx"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["allergen_tags"], name="ingredient_allergen_gin"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HouseholdUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "grams",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household_units_set",
                        to="recipes.ingredient",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "ingredient")},
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("name_alt", models.CharField(blank=True, default="", max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cuisine",
                    models.CharField(
                        choices=[
                            ("north_indian", "North Indian"),
                            ("south_indian", "South Indian"),
                            ("east_indian", "East Indian"),
                            ("west_indian", "West Indian"),
                            ("punjabi", "Punjabi"),
                            ("gujarati", "Gujarati"),
                            ("maharashtrian", "Maharashtrian"),
                            ("bengali", "Bengali"),
                            ("tamil", "Tamil"),
                            ("kerala", "Kerala"),
                            ("andhra", "Andhra"),
                            ("rajasthani", "Rajasthani"),
                            ("goan", "Goan"),
                            ("sindhi", "Sindhi"),
                            ("continental", "Continental"),
                            ("chinese_indo", "Indo-Chinese"),
                            ("pan_asian", "Pan-Asian"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "diet_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "allergen_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("prep_time_min", models.PositiveSmallIntegerField(default=0)),
                ("cook_time_min", models.PositiveSmallIntegerField(default=0)),
                (
                    "servings",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "estimated_difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "spice_level",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("medium", "Medium"),
                            ("hot", "Hot"),
                            ("very_hot", "Very Hot"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("instructions", models.JSONField(default=list)),
                ("image_url", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("seed", "Seed"),
                            ("ai_generated", "AI Generated"),
                            ("user_custom", "User Custom"),
                        ],
                        default="seed",
                        max_length=20,
                    ),
                ),
                ("cached_nutrition", models.JSONField(blank=True, null=True)),
                ("cached_calories_per_serving", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cached_cost_inr",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
                ),
                ("cost_known", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["meal_type"], name="recipes_rec_meal_ty_6971f5_idx"),
                    models.Index(fields=["cuisine"], name="recipes_rec_cuisine_0fee58_idx"),
                    models.Index(fields=["prep_time_min"], name="recipes_rec_prep_ti_ce6368_idx"),
                    models.Index(
                        fields=["estimated_difficulty"], name="recipes_rec_estimat_62001a_idx"
                    ),
                    models.Index(fields=["spice_level"], name="recipes_rec_spice_l_413b13_idx"),
                    models.Index(
                        fields=["cached_calories_per_serving"],
                        name="recipes_rec_cached__f92579_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["diet_tags"], name="recipe_diet_tags_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["allergen_tags"], name="recipe_allergen_gin"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "quantity_grams",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "display_quantity",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                (
                    "display_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="recipes.householdunit",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipe_usages",
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("recipe", "ingredient")},
            },
        ),
    ]
