# Generated by Django 5.1.15 on 2026-05-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="protein_source",
            field=models.CharField(
                choices=[
                    ("paneer", "Paneer"),
                    ("dal_legume", "Dal / Legume"),
                    ("egg", "Egg"),
                    ("chicken", "Chicken"),
                    ("mutton", "Mutton"),
                    ("fish", "Fish / Seafood"),
                    ("soy", "Soy / Tofu"),
                    ("none", "None"),
                ],
                db_index=True,
                default="none",
                max_length=20,
            ),
        ),
    ]
