# Generated by Django 5.1.15 on 2026-05-24 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0003_backfill_protein_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan_date", models.DateField()),
                (
                    "generated_by",
                    models.CharField(
                        choices=[("rules", "Rules"), ("ai", "AI")], default="rules", max_length=10
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("regeneration_count", models.JSONField(default=dict)),
                ("full_plan_regenerations", models.PositiveSmallIntegerField(default=0)),
                (
                    "breakfast",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "dinner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "lunch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "-plan_date"], name="mealplan_user_date_desc")
                ],
                "unique_together": {("user", "plan_date")},
            },
        ),
    ]
